name: your_project_name
description: A beautiful and responsive login and sign-up app.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0 # For custom fonts
  provider: ^6.0.5     # For state management (if needed later)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic